CREATE TABLE DEPARTMENT(
	DEPARTMENT_NAME VARCHAR2(255) NOT NULL,
	AVG_SALARY NUMBER
);

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT
VALUES('EXECUTIVE', 19333.33);
INSERT INTO DEPARTMENT
VALUES('ACCOUNTING', 10154.00);
INSERT INTO DEPARTMENT
VALUES('PUBLIC RELATIONS', 10000.00);
INSERT INTO DEPARTMENT
VALUES('MARKETING', 9500.00);
INSERT INTO DEPARTMENT
VALUES('SALES', 8955.88);
INSERT INTO DEPARTMENT
VALUES('FINANCE', 8601.33);

SELECT DEPARTMENT_NAME, FLOOR(AVG_SALARY)
FROM DEPARTMENT
WHERE AVG_SALARY >= 8000
ORDER BY AVG_SALARY DESC;






CREATE TABLE EMPLOYEES(
	NAME VARCHAR2(255),
	MANEGER_NAME VARCHAR2(255)
);
CREATE TABLE MANEGERS(
	NAME VARCHAR2(255),
	EMPLOYEE_NAME VARCHAR2(255)
);
INSERT INTO EMPLOYEES
VALUES('STEVE', '');
INSERT INTO EMPLOYEES
VALUES('NINA', 'STEVE');
INSERT INTO EMPLOYEES
VALUES('ALEX', 'STEVE');
INSERT INTO EMPLOYEES
VALUES('SEM', 'ALEX');
INSERT INTO EMPLOYEES
VALUES('MINSU', 'ALEX');

INSERT INTO MANEGERS
VALUES('', 'STEVE');
INSERT INTO MANEGERS
VALUES('STEVE', 'NINA');
INSERT INTO MANEGERS
VALUES('STEVE', 'ALEX');
INSERT INTO MANEGERS
VALUES('ALEX', 'SEM');
INSERT INTO MANEGERS
VALUES('ALEX', 'MINSU');

SELECT * FROM EMPLOYEES;
SELECT * FROM MANEGERS;
DROP TABLE EMPLOYEES;
DROP TABLE MANEGERS;

SELECT E.NAME 직원, NVL(M.NAME, 'CEO') 매니저
FROM EMPLOYEES E
	LEFT JOIN MANEGERS M
	ON E.NAME = M.EMPLOYEE_NAME;



CREATE TABLE TBL_MEMBERS(
	ID NUMBER CONSTRAINT PK_MEMBERS PRIMARY KEY,
	
	
);
CREATE TABLE TBL_DEPARTMENT(
	
);