-- DDL - ALTER 챕터

-- 동물 테이블
-- 이름, 나이, 색

CREATE SEQUENCE SEQ_ANIMAL
START WITH 1
INCREMENT BY 10;		-- 1부터 10씩 증가

CREATE TABLE TBL_ANIMAL(
	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
	ANIMAL_NAME VARCHAR(255) UNIQUE NOT NULL,
	ANIMAL_AGE NUMBER DEFAULT 0,
	ANIMAL_COLOR VARCHAR(255) NOT NULL
);

INSERT INTO TBL_ANIMAL 
VALUES(SEQ_ANIMAL.NEXTVAL, '진도니', 5, '갈색');
INSERT INTO TBL_ANIMAL 
VALUES(SEQ_ANIMAL.NEXTVAL, '치즈', 5, '주황색');

SELECT * FROM TBL_ANIMAL;




-- 컬럼 이름 변경
-- RENAME A TO B : 테이블의 이름 변경
-- RENAME COLUMN A TO B : 테이블 내의 컬럼 이름 변경
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_SPECIES;
SELECT * FROM TBL_ANIMAL;

ALTER TABLE TBL_ANIMAL RENAME TO TBL_PET;		-- A TO B에서 내 자신을 바꾸는 거니까 A 생략가능
SELECT * FROM TBL_PET;


-- 테이블이 바뀌면 PK, SEQUENCE, 컬럼명도 모두 바꿔야한다. 
-- 차라리 DROP하고 테이블 다시 만드는 게 낫지만 일단 ㄱㄱ
RENAME SEQ_ANIMAL TO SEQ_PET;
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_SPECIES TO PET_SPECIES;
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_AGE TO PET_AGE;
ALTER TABLE TBL_PET RENAME COLUMN ANIMAL_COLOR TO PET_COLOR;
SELECT * FROM TBL_PET;


-- PK는 이름을 바로 바꿀 수 없다.
-- PK를 삭제하고, 다시 추가해야한다.
-- 단, FK키가 참조하고 있는 경우 삭제할 수 없다. (개체 참조 도메인 무결성 중, 참조무결성에 저해)
ALTER TABLE TBL_PET DROP CONSTRAINT PK_ANIMAL;
-- 추가
ALTER TABLE TBL_PET ADD CONSTRAINT PK_PET PRIMARY KEY(ID);

DROP TABLE TBL_PET;
DROP SEQUENCE SEQ_PET;




CREATE SEQUENCE SEQ_PET;
CREATE TABLE TBL_PET(
	ID NUMBER,
	PET_NAME VARCHAR(255) UNIQUE NOT NULL,
	PET_AGE NUMBER DEFAULT 0,
	PET_COLOR VARCHAR(255) NOT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(ID)		-- 보통 PK는 분리 안하고 바로 한 줄로 입력하고, FK를 분리해서 쓴다.
);


-- ======================================================================

-- 자동차 테이블
CREATE SEQUENCE SEQ_CAR;
CREATE TABLE TBL_CAR (
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NUM NUMBER UNIQUE NOT NULL,
	CAR_BRAND VARCHAR(255) NOT NULL,
	CAR_RELEASEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CAR_COLOR CHAR(10),
	CAR_PRICE NUMBER
);
SELECT * FROM TBL_CAR;

INSERT INTO TBL_CAR (ID, CAR_NUM, CAR_BRAND, CAR_COLOR, CAR_PRICE)
VALUES(1, 346552, 'FORD', 'BLUE', 100000000);								-- 어떻게 타임스탬프 쓰지? ==> 디폴트라서 INSERT INTO문에서부터 변수로 안주면 된다. 
INSERT INTO TBL_CAR (ID, CAR_NUM, CAR_BRAND, CAR_COLOR, CAR_PRICE)
VALUES(SEQ_CAR.NEXTVAL, 904032, '람보르기니', 'RED', 500000000);				-- 시퀀스 안되는데? ==> INSERT INTO문에서 변수줘야 시퀀스 동작함.
SELECT * FROM TBL_CAR;

DROP TABLE TBL_CAR;
DROP SEQUENCE SEQ_CAR;


-- ======================================================================

-- 유저테이블, 게시글 테이블
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER
);
SELECT * FROM TBL_USER;

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	USER_ID NUMBER,										-- FK 지정하더라도 줄 바꾸면 , 붙여야 됨
	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)		-- FK_POST_USER 내가(POST) USER를 참조한다고 선언.
	REFERENCES TBL_USER(ID)								-- 래퍼런스가 되는 테이블의 컬럼을 지정.
);
SELECT * FROM TBL_POST;





-- =======================================================
-- 정규화 (테이블 분리) 챕터

-- 요구 사항
-- 회원이 존재하고 회원은 여러 상품을 구매할 수 있다.
-- DB시스템을 만들어라.
-- 회원테이블 이름, 나이, 연락처, 주소, 등급
-- 상품테이블 상품명, 금액, 재고
-- 구매테이블 구매일자...

-- 요구사항
-- 상품 판매자(TBL_SELLER)가 상품 구매자(TBL_BUYER)에게
-- 배송(TBL_DELEVERY)을 할 수 있는 기능이 필요해요.
-- 판매자: 음료, 음료 종류, 음료 크기, 만든 날짜
-- 구매자: 이름, 주소, 연락처, 음료, 수량
-- 배송: 주문일자, 주문수량, 배송여부, 판매자, 구매자

-- 요구사항
-- 사용자(TBL_GOODS_USER): 이름 주소 연락처
-- 굿즈(TBL_GOODS): 이름 크기 가격 재고
-- 선물하기: 받는사람이름 주소 연락처 사용자 굿즈

--=============================================
/*
	요구사항
	유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
	아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
	체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
	아이들은 여러 번 체험학습에 등록할 수 있어요.
*/

-- 아이 
-- 이름, 나이, 성별
CREATE SEQUENCE SEQ_CHILD;
CREATE TABLE TBL_CHILD(
	ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
	CHILD_NAME VARCHAR2(255) NOT NULL,
	CHILD_AGE NUMBER,
	CHILD_GENDER CHAR(5)
);

-- 부모 FK
-- 이름, 나이, 주소, 전화번호, 성별
CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(255) NOT NULL,
	PARENT_AGE NUMBER,
	PARENT_ADDRESS VARCHAR2(255),
	PARENT_PHONE VARCHAR2(255) NOT NULL,
	PARNET_GENDER CHAR(5),
	CHILD_ID NUMBER,
	CONSTRAINT FK_PARENT_CHILD FOREIGN KEY(CHILD_ID)
	REFERENCES TBL_CHILD(ID)
);

-- 체험학습
-- 제목, 체험학습 내용
CREATE SEQUENCE SEQ_FIELD_TRIP;
CREATE TABLE TBL_FIELD_TRIP(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
	FIELD_TRIP_TITLE VARCHAR2(255),
	FIELD_TRIP_CONTENT VARCHAR2(255),
	FIELD_TRIP_NUMBER NUMBER
);

-- 체험학습 이미지 FK
CREATE SEQUENCE SEQ_FIELD_TRIP_FILE;
CREATE TABLE TBL_FIELD_TRIP_FILE(
	ID NUMBER CONSTRAINT PK_FIELD_TRIP_FILE PRIMARY KEY,
	FIELD_TRIP_FILE_NAME VARCHAR2(255),
	FIELD_TRIP_FILE_PATH VARCHAR2(255),
	FIELD_TRIP_ID NUMBER,
	CONSTRAINT FK_FIELD_TRIP_FILE_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
	REFERENCES TBL_FIELD_TRIP(ID)
);
-- 신청 FK
CREATE SEQUENCE SEQ_APPLY;
CREATE TABLE TBL_APPLY(
	ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
	APPLY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CHILD_ID NUMBER,
	FIELD_TRIP_ID NUMBER,
	CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
	REFERENCES TBL_CHILD(ID),
	CONSTRAINT FK_APPLY_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
	REFERENCES TBL_FIELD_TRIP(ID)
);

/*

	요구사항
	안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
	광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
	광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
	기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/

-- 정답 풀이
-- 중복돼서 분리 해야할 거 
-- 광고의 카테고리가 중복될 수 있고 대중소로 여러 개 나오니까 (카테고리 테이블로 분리), ==> 대 중 소 각각 테이블 만들어야 됨
-- 기업도 여러 기업종류에 속할 수 있는건가??		==> 나눌 필요없다. 그냥 4개값을 CONSTRAINT BAN_TYPE CHECK(COMPANY_KIND IN ('스타트업', '중소기업', '중견기업', 대기업')으로 주면 됨
	
-- 신청 테이블 생성 (FK : 회사ID, 광고ID)

-- 회사
-- 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255) NOT NULL,
	COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
	COMPANY_PHONE VARCHAR2(255),
	COMPANY_TYPE VARCHAR2(255) NOT NULL
	CONSTRAINT BAN_TYPE CHECK(COMPANY_TYPE IN ('스타트업', '중소기업', '중견기업', '대기업'))
);

-- 광고
CREATE SEQUENCE SEQ_ADVERTISEMENT;
CREATE TABLE TBL_ADVERTISEMENT(
	ID NUMBER CONSTRAINT PK_ADVERTISEMENT PRIMARY KEY,
	ADVERTISEMENT_TITLE VARCHAR2(255) NOT NULL,
	ADVERTISEMENT_CONTENT VARCHAR2(255) NOT NULL
);

-- 신청 FK
-- 대카테고리 FK
CREATE SEQUENCE SEQ_TBL_CATEGORY_A;
CREATE TABLE TBL_CATEGORY_A(
	ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
	CATEGORY_A_NAME VARCHAR2(255) NOT NULL,
	ADVERTISEMENT_ID NUMBER,
	CONSTRAINT FK_CATEGORY_A_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
	REFERENCES TBL_ADVERTISEMENT(ID)
);

-- 중카테고리 FK
CREATE SEQUENCE SEQ_CATEGODY_B;
CREATE TABLE TBL_CATEGORY_B(
	ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
	CATEGORY_B_NAME VARCHAR2(255) NOT NULL,
	CATEGORY_A_ID NUMBER,
	CONSTRAINT FK_CATEGORY_B_CATEGOGY_A FOREIGN KEY(CATEGORY_A_ID)
	REFERENCES TBL_CATEGORY_A(ID)
);

-- 소카테고리 FK
CREATE SEQUENCE SEQ_CATEGORY_C;
CREATE TABLE TBL_CATEGORY_C(
	ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
	CATEGORY_B_ID NUMBER,
	CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
	REFERENCES TBL_CATEGORY_B(ID)
);

-- 신청 테이블
CREATE SEQUENCE SEQ_ADVERTISEMENT_APPLY;
CREATE TABLE TBL_ADVERTISEMENT_APPLY(
	ID NUMBER CONSTRAINT PK_ADVERTISEMENT_APPLY PRIMARY KEY,
	COMPANY_ID NUMBER,
	ADVERTISEMENT_ID NUMBER,
	CONSTRAINT FK_ADVERTISEMENT_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVERTISEMENT_APPLY_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
	REFERENCES TBL_ADVERTISEMENT(ID)
);







