CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR2(255)
);




-- 상품 PRODUCT
-- 상품이름, 가격, 재고, 설명
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,	-- 초기값 넣기 : 제약조건 CONSTRAINT 중 DEFAULT
	PRODUCT_EXPLAIN VARCHAR2(255) 
);


-- SQL언어의 값은 '' 싱글쿼터를 사용한다.
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(1, '이승찬의 맥북', 1500000);
SELECT * FROM TBL_PRODUCT;

-- ↑↓ 도메인 무결성 		왜???
--INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
--VALUES(1, '배승원의 그램', 15000);
--SELECT * FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램', 20000);
SELECT * FROM TBL_PRODUCT;

-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;
SELECT * FROM TBL_PRODUCT;

-- 컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;
SELECT * FROM TBL_PRODUCT;

DROP TABLE TBL_PRODUCT;
DROP SEQUENCE SEQ_PRODUCT;





-- MEMBER 테이블
-- ID, 이름, 나이, 성별, 주소
-- ID는 시퀀스로 관리
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255),
	MEMBER_AGE NUMBER,
	MEMBER_GENDER VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255)
);

-- 사용자를 2명 추가
INSERT INTO TBL_MEMBER (ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES (1, '박웅규', 30, '남', '송파');
SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER (ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES (SEQ_MEMBER.NEXTVAL, '김혁', 22, '여', '잠원');
SELECT * FROM TBL_MEMBER;

-- 등급 컬럼 CHAR 타입으로 추가
ALTER TABLE TBL_MEMBER ADD MEMBER_GRADE CHAR;
SELECT * FROM TBL_MEMBER;

-- 등급 컬럼을 VARCAHR2 타입으로 변경
ALTER TABLE TBL_MEMBER MODIFY MEMBER_GRADE VARCHAR2(255);

-- 등급 컬럼 타입 변경여부 확인
SELECT column_name, data_type, data_length
FROM user_tab_columns
WHERE table_name = 'TBL_MEMBER';

-- 등급 컬럼 삭제
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_GRADE;
SELECT * FROM TBL_MEMBER;

DROP TABLE TBL_MEMBER;
DROP SEQUENCE SEQ_MEMBER;


