CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER 
VALUES(SEQ_MEMBER.NEXTVAL, 'ss03056', '1234', '박웅규', 22, '서울 송파');